/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ApiAlpacaJournalRouteImport } from './routes/api/alpaca-journal'
import { Route as ApiAlpacaPositionsRouteImport } from './routes/api/alpaca-positions'
import { Route as ApiOrderRouteImport } from './routes/api/order'
import { Route as ApiPortfolioHistoryRouteImport } from './routes/api/portfolio-history'
import { Route as ApiRiskRouteImport } from './routes/api/risk'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiCronDailyScanRouteImport } from './routes/api/cron/daily-scan'
import { Route as ApiCronHistoryRouteImport } from './routes/api/cron/history'
import { Route as ApiCronTestRouteImport } from './routes/api/cron/test'
import { Route as ApiTelegramTestRouteImport } from './routes/api/telegram/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlpacaJournalRoute = ApiAlpacaJournalRouteImport.update({
  id: '/api/alpaca-journal',
  path: '/api/alpaca-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlpacaPositionsRoute = ApiAlpacaPositionsRouteImport.update({
  id: '/api/alpaca-positions',
  path: '/api/alpaca-positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioHistoryRoute = ApiPortfolioHistoryRouteImport.update({
  id: '/api/portfolio-history',
  path: '/api/portfolio-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskRoute = ApiRiskRouteImport.update({
  id: '/api/risk',
  path: '/api/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyScanRoute = ApiCronDailyScanRouteImport.update({
  id: '/api/cron/daily-scan',
  path: '/api/cron/daily-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHistoryRoute = ApiCronHistoryRouteImport.update({
  id: '/api/cron/history',
  path: '/api/cron/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTestRoute = ApiCronTestRouteImport.update({
  id: '/api/cron/test',
  path: '/api/cron/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramTestRoute = ApiTelegramTestRouteImport.update({
  id: '/api/telegram/test',
  path: '/api/telegram/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/scanner': typeof ScannerRoute
  '/api/alpaca-journal': typeof ApiAlpacaJournalRoute
  '/api/alpaca-positions': typeof ApiAlpacaPositionsRoute
  '/api/order': typeof ApiOrderRoute
  '/api/portfolio-history': typeof ApiPortfolioHistoryRoute
  '/api/risk': typeof ApiRiskRoute
  '/api/scan': typeof ApiScanRoute
  '/api/cron/daily-scan': typeof ApiCronDailyScanRoute
  '/api/cron/history': typeof ApiCronHistoryRoute
  '/api/cron/test': typeof ApiCronTestRoute
  '/api/telegram/test': typeof ApiTelegramTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/scanner': typeof ScannerRoute
  '/api/alpaca-journal': typeof ApiAlpacaJournalRoute
  '/api/alpaca-positions': typeof ApiAlpacaPositionsRoute
  '/api/order': typeof ApiOrderRoute
  '/api/portfolio-history': typeof ApiPortfolioHistoryRoute
  '/api/risk': typeof ApiRiskRoute
  '/api/scan': typeof ApiScanRoute
  '/api/cron/daily-scan': typeof ApiCronDailyScanRoute
  '/api/cron/history': typeof ApiCronHistoryRoute
  '/api/cron/test': typeof ApiCronTestRoute
  '/api/telegram/test': typeof ApiTelegramTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/scanner': typeof ScannerRoute
  '/api/alpaca-journal': typeof ApiAlpacaJournalRoute
  '/api/alpaca-positions': typeof ApiAlpacaPositionsRoute
  '/api/order': typeof ApiOrderRoute
  '/api/portfolio-history': typeof ApiPortfolioHistoryRoute
  '/api/risk': typeof ApiRiskRoute
  '/api/scan': typeof ApiScanRoute
  '/api/cron/daily-scan': typeof ApiCronDailyScanRoute
  '/api/cron/history': typeof ApiCronHistoryRoute
  '/api/cron/test': typeof ApiCronTestRoute
  '/api/telegram/test': typeof ApiTelegramTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journal'
    | '/scanner'
    | '/api/alpaca-journal'
    | '/api/alpaca-positions'
    | '/api/order'
    | '/api/portfolio-history'
    | '/api/risk'
    | '/api/scan'
    | '/api/cron/daily-scan'
    | '/api/cron/history'
    | '/api/cron/test'
    | '/api/telegram/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journal'
    | '/scanner'
    | '/api/alpaca-journal'
    | '/api/alpaca-positions'
    | '/api/order'
    | '/api/portfolio-history'
    | '/api/risk'
    | '/api/scan'
    | '/api/cron/daily-scan'
    | '/api/cron/history'
    | '/api/cron/test'
    | '/api/telegram/test'
  id:
    | '__root__'
    | '/'
    | '/journal'
    | '/scanner'
    | '/api/alpaca-journal'
    | '/api/alpaca-positions'
    | '/api/order'
    | '/api/portfolio-history'
    | '/api/risk'
    | '/api/scan'
    | '/api/cron/daily-scan'
    | '/api/cron/history'
    | '/api/cron/test'
    | '/api/telegram/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalRoute: typeof JournalRoute
  ScannerRoute: typeof ScannerRoute
  ApiAlpacaJournalRoute: typeof ApiAlpacaJournalRoute
  ApiAlpacaPositionsRoute: typeof ApiAlpacaPositionsRoute
  ApiOrderRoute: typeof ApiOrderRoute
  ApiPortfolioHistoryRoute: typeof ApiPortfolioHistoryRoute
  ApiRiskRoute: typeof ApiRiskRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiCronDailyScanRoute: typeof ApiCronDailyScanRoute
  ApiCronHistoryRoute: typeof ApiCronHistoryRoute
  ApiCronTestRoute: typeof ApiCronTestRoute
  ApiTelegramTestRoute: typeof ApiTelegramTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alpaca-journal': {
      id: '/api/alpaca-journal'
      path: '/api/alpaca-journal'
      fullPath: '/api/alpaca-journal'
      preLoaderRoute: typeof ApiAlpacaJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alpaca-positions': {
      id: '/api/alpaca-positions'
      path: '/api/alpaca-positions'
      fullPath: '/api/alpaca-positions'
      preLoaderRoute: typeof ApiAlpacaPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio-history': {
      id: '/api/portfolio-history'
      path: '/api/portfolio-history'
      fullPath: '/api/portfolio-history'
      preLoaderRoute: typeof ApiPortfolioHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/risk': {
      id: '/api/risk'
      path: '/api/risk'
      fullPath: '/api/risk'
      preLoaderRoute: typeof ApiRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-scan': {
      id: '/api/cron/daily-scan'
      path: '/api/cron/daily-scan'
      fullPath: '/api/cron/daily-scan'
      preLoaderRoute: typeof ApiCronDailyScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/history': {
      id: '/api/cron/history'
      path: '/api/cron/history'
      fullPath: '/api/cron/history'
      preLoaderRoute: typeof ApiCronHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/test': {
      id: '/api/cron/test'
      path: '/api/cron/test'
      fullPath: '/api/cron/test'
      preLoaderRoute: typeof ApiCronTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/test': {
      id: '/api/telegram/test'
      path: '/api/telegram/test'
      fullPath: '/api/telegram/test'
      preLoaderRoute: typeof ApiTelegramTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalRoute: JournalRoute,
  ScannerRoute: ScannerRoute,
  ApiAlpacaJournalRoute: ApiAlpacaJournalRoute,
  ApiAlpacaPositionsRoute: ApiAlpacaPositionsRoute,
  ApiOrderRoute: ApiOrderRoute,
  ApiPortfolioHistoryRoute: ApiPortfolioHistoryRoute,
  ApiRiskRoute: ApiRiskRoute,
  ApiScanRoute: ApiScanRoute,
  ApiCronDailyScanRoute: ApiCronDailyScanRoute,
  ApiCronHistoryRoute: ApiCronHistoryRoute,
  ApiCronTestRoute: ApiCronTestRoute,
  ApiTelegramTestRoute: ApiTelegramTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
