/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAlpacaPositionsRouteImport } from './routes/api/alpaca-positions'
import { Route as ApiScanRouteImport } from './routes/api/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlpacaPositionsRoute = ApiAlpacaPositionsRouteImport.update({
  id: '/api/alpaca-positions',
  path: '/api/alpaca-positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/alpaca-positions': typeof ApiAlpacaPositionsRoute
  '/api/scan': typeof ApiScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/alpaca-positions': typeof ApiAlpacaPositionsRoute
  '/api/scan': typeof ApiScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/alpaca-positions': typeof ApiAlpacaPositionsRoute
  '/api/scan': typeof ApiScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/alpaca-positions' | '/api/scan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/alpaca-positions' | '/api/scan'
  id: '__root__' | '/' | '/api/alpaca-positions' | '/api/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAlpacaPositionsRoute: typeof ApiAlpacaPositionsRoute
  ApiScanRoute: typeof ApiScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alpaca-positions': {
      id: '/api/alpaca-positions'
      path: '/api/alpaca-positions'
      fullPath: '/api/alpaca-positions'
      preLoaderRoute: typeof ApiAlpacaPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAlpacaPositionsRoute: ApiAlpacaPositionsRoute,
  ApiScanRoute: ApiScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
